apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappwithsidecat
  labels:
    app: lol
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
        zone: us-est-coast
        cluster: test-cluster1
        rack: rack-22
      annotations:
        build: best
        builder: tim
    spec:
      containers:
        - name: webapp
          image: tthebst/flask-webapp
          ports:
            - containerPort: 8088
          env:
            - name: accesstoken_ipinfo
              value: "infoip passwd here ********"
        - name: flask-podinfo-sidecar
          image: tthebst/flask-podinfo-sidecar
          ports:
            - containerPort: 8080
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
              - path: "name"
                fieldRef:
                  fieldPath: metadata.name
