resources:
  - name: demoapp
    type: git
    source:
      uri: ((git-repo))
      branch: master  
  - name: flask-podinfo-sidecar
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: tthebst/flask-podinfo-sidecar
  - name: flask-webapp
    type: docker-image
    source:
      email: ((docker-hub-email))
      username: ((docker-hub-username))
      password: ((docker-hub-password))
      repository: tthebst/flask-webapp


jobs:
- name: tests
  plan:
  - get: demoapp
    trigger: true
  - task: flask-test-podinfo
    file: demoapp/concourse/tasks/flask-test-podinfo-sidecat.yml
  - task: flask-test-webapp
    file: demoapp/concourse/tasks/flask-test-webapp.yml
  - task: flask-test-webapp-javascript
    file: demoapp/concourse/tasks/flask-webapp-js.yml
- name: security
  plan:
  - get: demoapp
    passed: [tests]
    trigger: true
  - task: check code formatting
    file: demoapp/concourse/tasks/check-code.yml
  - task: check for security flaws in python code
    file: demoapp/concourse/tasks/check-security.yml
- name: build
  plan:
  - get: demoapp
    passed: [security]
    trigger: true
  - put: flask-webapp
    params:
      build: demoapp/flask_webapp
  - put: flask-podinfo-sidecar
    params:
      build: demoapp/flask_podinfo_sidecar