resources:
    - name: demoapp
      type: git
      source:
        uri: https://github.com/tthebst/demoapp
        branch: master
    
jobs:
- name: run tests on application
  plan:
  - get: demoapp
    trigger: true
  - task: flask-test-podinfo
    file: demoapp/concourse/tasks/flask-test-podinfo-sidecat.yml
  - task: flask-test-webapp
    file: demoapp/concourse/tasks/flask-test-webapp.yml