platform: linux
image_resource:
    type: docker-image
    source:
        repository: python
        tag: '3.7.7'
inputs:
- name: demoapp
run:
  path: sh
  args:
  - -exc
  - pip install -r demoapp/flask_webapp/requirements.txt && find ./demoapp -type f -name "*.py" | xargs pylint --exit-zero

