platform: linux
image_resource:
    type: docker-image
    source:
        repository: python
        tag: '3.7.7'
inputs:
- name: demoapp
run:
  path: sh
  args:
  - -exc
  - pip install -r demoapp/flask_webapp/requirements.txt && pip install bandit && cd demoapp && bandit -lll  -r . -x ./flask_webapp/tests/,./flask_podinfo_sidecar/tests/

