platform: linux
image_resource:
    type: docker-image
    source:
        repository: node
        tag: '13.10.1'
inputs:
- name: demoapp
run:
  path: sh
  args:
  - -exc
  - cd demoapp/flask_webapp && npm install --save-dev jest &&  npm run test

